---
- name: Executes DRP in case of primary site or primary db failure
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Configures Automation Controller nodes
      when: inventory_hostname in groups['automation_controller']
      block:
        - name: Stops automation controller services on Control Nodes
          ansible.builtin.service:
            name: automation-controller.service
            state: stopped

        - name: Changes Controller DB configuration
          ansible.builtin.replace:
            path: /etc/tower/conf.d/postgres.py
            regexp: "'{{ hostvars['db_primary']['ansible_facts']['fqdn'] }}'"
            replace: "'{{ hostvars['db_secondary']['ansible_facts']['fqdn'] }}'"
          notify: Restart automation controller services

    - name: Configures Event Driven Controller node
      when: inventory_hostname in groups['event_driven_controller']
      block:
        - name: Stops automation controller services on Control Nodes
          ansible.builtin.service:
            name: automation-eda-controller.service
            state: stopped

        - name: Changes Event Driven Controller DB configuration
          ansible.builtin.replace:
            path: /etc/ansible-automation-platform/eda/environment
            regexp: "^(EDA_DB_HOST={{ hostvars['db_primary']['ansible_facts']['fqdn'] }})$"
            replace: "EDA_DB_HOST={{ hostvars['db_secondary']['ansible_facts']['fqdn'] }}"
          notify: Restart automation eda controller service



    - name: Configures Private Automation Hub nodes
      when: inventory_hostname in groups['automation_hub']
      block:
        - name: Stops automation hub services on Hub Nodes
          ansible.builtin.service:
            name: "{{ item }}"
            state: stopped
          loop:
            - pulpcore.service
            - pulpcore-api.service
            - pulpcore-content.service
            - pulpcore-worker@1.service
            - pulpcore-worker@2.service
            - nginx.service
            - redis.service

        - name: Changes Hub DB configuration
          ansible.builtin.replace:
            path: /etc/pulp/settings.py
            regexp: "'{{ hostvars['db_primary']['ansible_facts']['fqdn'] }}'"
            replace: "'{{ hostvars['db_secondary']['ansible_facts']['fqdn'] }}'"
          notify: Restart automation hub services

    - name: Ensures secondary DB is promoted
      when: inventory_hostname == "db_secondary"
      block:
        - name: Promotes DB secondary to primary
          become_user: postgres
          ansible.builtin.command:
            cmd: /usr/bin/pg_ctl promote -D /var/lib/pgsql/data


  handlers:
    - name: Restart automation controller services
      ansible.builtin.service:
        name: automation-controller.service
        state: restarted

    - name: Restart automation eda controller service
      ansible.builtin.service:
        name: automation-eda-controller.service
        state: restarted

    - name: Restart automation hub services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - pulpcore.service
        - pulpcore-api.service
        - pulpcore-content.service
        - pulpcore-worker@1.service
        - pulpcore-worker@2.service
        - nginx.service
        - redis.service

